[package]
name = "bongocat-app"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
publish.workspace = true
build = "build.rs"

[dependencies]
bongocat-config.workspace = true
bongocat-model.workspace = true
bongocat-overlay.workspace = true
bongocat-render.workspace = true
bongocat-runtime.workspace = true

[dev-dependencies]
tempfile.workspace = true

[lints]
workspace = true
