LangString addOrReinstall ${LANG_VIETNAMESE} "Thêm hoặc cài đặt lại thành phần"
LangString alreadyInstalled ${LANG_VIETNAMESE} "Đã được cài đặt"
LangString alreadyInstalledLong ${LANG_VIETNAMESE} "${PRODUCTNAME} ${VERSION} đã được cài đặt. Chọn thao tác bạn muốn thực hiện rồi nhấn Tiếp theo để tiếp tục."
LangString appRunning ${LANG_VIETNAMESE} "${PRODUCTNAME} đang chạy! Vui lòng đóng ứng dụng trước rồi thử lại."
LangString appRunningOkKill ${LANG_VIETNAMESE} "${PRODUCTNAME} đang chạy!$\nNhấn OK để buộc đóng ứng dụng"
LangString chooseMaintenanceOption ${LANG_VIETNAMESE} "Chọn thao tác bảo trì cần thực hiện."
LangString choowHowToInstall ${LANG_VIETNAMESE} "Chọn cách bạn muốn cài đặt ${PRODUCTNAME}."
LangString createDesktop ${LANG_VIETNAMESE} "Tạo lối tắt trên màn hình nền"
LangString dontUninstall ${LANG_VIETNAMESE} "Không gỡ cài đặt"
LangString dontUninstallDowngrade ${LANG_VIETNAMESE} "Không gỡ cài đặt (trình cài đặt này không cho phép hạ cấp mà không gỡ cài đặt)"
LangString failedToKillApp ${LANG_VIETNAMESE} "Không thể đóng ${PRODUCTNAME}. Vui lòng đóng ứng dụng trước rồi thử lại"
LangString newerVersionInstalled ${LANG_VIETNAMESE} "Một phiên bản mới hơn của ${PRODUCTNAME} đã được cài đặt! Không nên cài đặt phiên bản cũ hơn. Nếu bạn thật sự muốn cài đặt phiên bản cũ này, nên gỡ cài đặt phiên bản hiện tại trước. Chọn thao tác bạn muốn thực hiện rồi nhấn Tiếp theo để tiếp tục."
LangString older ${LANG_VIETNAMESE} "cũ hơn"
LangString olderOrUnknownVersionInstalled ${LANG_VIETNAMESE} "Một phiên bản $R4 của ${PRODUCTNAME} đã được cài đặt trên hệ thống. Nên gỡ cài đặt phiên bản hiện tại trước khi cài đặt. Chọn thao tác bạn muốn thực hiện rồi nhấn Tiếp theo để tiếp tục."
LangString silentDowngrades ${LANG_VIETNAMESE} "Trình cài đặt này không cho phép hạ cấp nên không thể tiếp tục ở chế độ cài đặt im lặng. Vui lòng dùng trình cài đặt có giao diện đồ họa.$\n"
LangString unableToUninstall ${LANG_VIETNAMESE} "Không thể gỡ cài đặt!"
LangString uninstallApp ${LANG_VIETNAMESE} "Gỡ cài đặt ${PRODUCTNAME}"
LangString uninstallBeforeInstalling ${LANG_VIETNAMESE} "Gỡ cài đặt trước khi cài đặt"
LangString unknown ${LANG_VIETNAMESE} "không xác định"
LangString deleteAppData ${LANG_VIETNAMESE} "Xóa dữ liệu ứng dụng"