[package]
name = "bongocat-ui"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
publish.workspace = true

[dependencies]
async-channel.workspace = true
bongocat-config.workspace = true

[target.'cfg(any(target_os = "macos", target_os = "windows"))'.dependencies]
bongocat-platform.workspace = true
gpui.workspace = true
guise-ui.workspace = true
raw-window-handle.workspace = true

[lints]
workspace = true
