use crate::{SystemMenuAction, SystemMenuError};
use objc2::{
    DefinedClass, MainThreadMarker, MainThreadOnly, define_class, msg_send, rc::Retained,
    runtime::AnyObject, sel,
};
use objc2_app_kit::{NSMenu, NSMenuItem, NSStatusBar, NSStatusItem, NSVariableStatusItemLength};
use objc2_foundation::{NSObject, NSObjectProtocol, NSString};
use std::sync::mpsc::{self, Receiver, Sender};

struct SystemMenuTargetIvars {
    sender: Sender<SystemMenuAction>,
}

define_class!(
    // SAFETY: NSObject has no subclassing requirements. The sender is dropped
    // only after AppKit has released every weak target reference.
    #[unsafe(super = NSObject)]
    #[thread_kind = MainThreadOnly]
    #[ivars = SystemMenuTargetIvars]
    struct SystemMenuTarget;

    // SAFETY: NSObjectProtocol has no additional safety requirements.
    unsafe impl NSObjectProtocol for SystemMenuTarget {}

    impl SystemMenuTarget {
        #[unsafe(method(openSettings:))]
        fn open_settings(&self, _sender: Option<&AnyObject>) {
            let _ = self.ivars().sender.send(SystemMenuAction::OpenSettings);
        }

        #[unsafe(method(toggleOverlayVisibility:))]
        fn toggle_overlay_visibility(&self, _sender: Option<&AnyObject>) {
            let _ = self
                .ivars()
                .sender
                .send(SystemMenuAction::ToggleOverlayVisibility);
        }

        #[unsafe(method(quit:))]
        fn quit(&self, _sender: Option<&AnyObject>) {
            let _ = self.ivars().sender.send(SystemMenuAction::Quit);
        }
    }
);

impl SystemMenuTarget {
    fn new(mtm: MainThreadMarker, sender: Sender<SystemMenuAction>) -> Retained<Self> {
        let target = Self::alloc(mtm).set_ivars(SystemMenuTargetIvars { sender });
        // SAFETY: this invokes NSObject's designated initializer with the
        // signature generated by objc2.
        unsafe { msg_send![super(target), init] }
    }
}

pub struct SystemMenu {
    status_bar: Retained<NSStatusBar>,
    status_item: Option<Retained<NSStatusItem>>,
    menu: Retained<NSMenu>,
    target: Retained<SystemMenuTarget>,
    receiver: Receiver<SystemMenuAction>,
}

impl SystemMenu {
    pub fn start() -> Result<Self, SystemMenuError> {
        Self::start_with_visibility(true)
    }

    pub fn start_with_visibility(visible: bool) -> Result<Self, SystemMenuError> {
        let mtm = MainThreadMarker::new().ok_or(SystemMenuError::WrongThread)?;
        let (sender, receiver) = mpsc::channel();
        let target = SystemMenuTarget::new(mtm, sender);
        let status_bar = NSStatusBar::systemStatusBar();
        let menu = NSMenu::initWithTitle(NSMenu::alloc(mtm), &NSString::from_str("BongoCat"));
        let empty = NSString::from_str("");
        // SAFETY: openSettings: is implemented by SystemMenuTarget with the
        // exact target/action ABI and the empty key equivalent is valid.
        let open_settings = unsafe {
            NSMenuItem::initWithTitle_action_keyEquivalent(
                NSMenuItem::alloc(mtm),
                &NSString::from_str("Open Settings"),
                Some(sel!(openSettings:)),
                &empty,
            )
        };
        // SAFETY: `target` implements the exact selector assigned above and
        // remains retained by SystemMenu longer than the weak target property.
        unsafe { open_settings.setTarget(Some(&target)) };
        menu.addItem(&open_settings);

        // SAFETY: toggleOverlayVisibility: is implemented by SystemMenuTarget
        // with the exact target/action ABI and the empty key equivalent is valid.
        let toggle_overlay = unsafe {
            NSMenuItem::initWithTitle_action_keyEquivalent(
                NSMenuItem::alloc(mtm),
                &NSString::from_str("Show/Hide BongoCat"),
                Some(sel!(toggleOverlayVisibility:)),
                &empty,
            )
        };
        // SAFETY: `target` implements the exact selector assigned above and
        // remains retained by SystemMenu longer than the weak target property.
        unsafe { toggle_overlay.setTarget(Some(&target)) };
        menu.addItem(&toggle_overlay);
        menu.addItem(&NSMenuItem::separatorItem(mtm));

        // SAFETY: quit: is implemented by SystemMenuTarget with the exact
        // target/action ABI and the empty key equivalent is valid.
        let quit = unsafe {
            NSMenuItem::initWithTitle_action_keyEquivalent(
                NSMenuItem::alloc(mtm),
                &NSString::from_str("Quit BongoCat"),
                Some(sel!(quit:)),
                &empty,
            )
        };
        // SAFETY: `target` implements the exact selector assigned above and
        // remains retained by SystemMenu longer than the weak target property.
        unsafe { quit.setTarget(Some(&target)) };
        menu.addItem(&quit);
        let mut system_menu = Self {
            status_bar,
            status_item: None,
            menu,
            target,
            receiver,
        };
        if visible {
            system_menu.install_status_item()?;
        }
        Ok(system_menu)
    }

    pub fn try_recv(&self) -> Option<SystemMenuAction> {
        self.receiver.try_recv().ok()
    }

    pub fn is_visible(&self) -> bool {
        self.status_item.is_some()
    }

    pub fn set_visible(&mut self, visible: bool) -> Result<(), SystemMenuError> {
        if visible == self.is_visible() {
            return Ok(());
        }
        if visible {
            self.install_status_item()
        } else {
            self.remove_status_item();
            Ok(())
        }
    }

    #[doc(hidden)]
    pub fn request_action_for_smoke(
        &self,
        action: SystemMenuAction,
    ) -> Result<(), SystemMenuError> {
        // SAFETY: both selectors are implemented by SystemMenuTarget with the
        // exact sender argument ABI. Dispatching through Objective-C exercises
        // the same target/action path as a real NSMenuItem selection.
        unsafe {
            match action {
                SystemMenuAction::OpenSettings => {
                    let _: () = msg_send![&*self.target, openSettings: None::<&AnyObject>];
                }
                SystemMenuAction::ToggleOverlayVisibility => {
                    let _: () =
                        msg_send![&*self.target, toggleOverlayVisibility: None::<&AnyObject>];
                }
                SystemMenuAction::Quit => {
                    let _: () = msg_send![&*self.target, quit: None::<&AnyObject>];
                }
            }
        }
        Ok(())
    }

    pub fn shutdown(mut self) -> Result<(), SystemMenuError> {
        self.remove_status_item();
        Ok(())
    }

    fn remove_status_item(&mut self) {
        if let Some(status_item) = self.status_item.take() {
            status_item.setMenu(None);
            self.status_bar.removeStatusItem(&status_item);
        }
    }

    fn install_status_item(&mut self) -> Result<(), SystemMenuError> {
        let mtm = MainThreadMarker::new().ok_or(SystemMenuError::WrongThread)?;
        let status_item = self
            .status_bar
            .statusItemWithLength(NSVariableStatusItemLength);
        let Some(button) = status_item.button(mtm) else {
            self.status_bar.removeStatusItem(&status_item);
            return Err(SystemMenuError::StatusItemCreateFailed);
        };
        button.setTitle(&NSString::from_str("BC"));
        button.setToolTip(Some(&NSString::from_str("BongoCat")));
        status_item.setMenu(Some(&self.menu));
        self.status_item = Some(status_item);
        Ok(())
    }
}

impl Drop for SystemMenu {
    fn drop(&mut self) {
        self.remove_status_item();
    }
}
