[package]
name = "bongocat-storage"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
publish.workspace = true

[dependencies]
atomic-write-file.workspace = true

[dev-dependencies]
tempfile.workspace = true

[lints]
workspace = true
